name: Get Activation File

on:
  workflow_dispatch:

jobs:
  activation:
    name: Request Activation File (.alf) 🔑
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Request activation file
        uses: game-ci/unity-builder@v4
        with:
          unityVersion: 6000.0.23f1
          versioning: None
          buildMethod: GameCI.Editor.Build.ManualActivation.WriteAlf
          customParameters: -logfile /dev/stdout
      - uses: actions/upload-artifact@v4
        with:
          name: activation-file
          path: ./*.alf
