name: Get Activation File

on:
  workflow_dispatch:

jobs:
  activation:
    name: Request Activation File (.alf) 🔑
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Request activation file
        run: |
          # Criar o arquivo de ativação e garantir que ele esteja no diretório atual
          docker run --rm \
            -v "$(pwd):/project" \
            unityci/editor:ubuntu-2022.3.20f1-base-3 \
            unity-editor \
              -batchmode \
              -nographics \
              -createManualActivationFile \
              -logfile /dev/stdout \
              -quit
          
          # Mover de dentro do projeto para a raiz se necessário
          find . -name "*.alf" -exec mv {} . \;
          
      - name: Rename and Upload
        run: |
          ls -R
      - uses: actions/upload-artifact@v4
        with:
          name: activation-file
          path: "**/*.alf"
