name: Build project

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    name: Build for Android 📱
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - uses: actions/cache@v4
        with:
          path: Library
          key: Library-Android
          restore-keys: |
            Library-

      # Tentar ativar a licença na hora
      - name: Activate Unity License
        uses: game-ci/unity-license-activate@main
        id: activate
        env:
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}

      - name: Build project
        uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ steps.activate.outputs.unityLicense }}
        with:
          targetPlatform: Android
          unityVersion: 6000.0.23f1
          androidAppBundle: false
          androidExportType: 'androidPackage'
